// Generated by CoffeeScript 2.3.1
(function() {
  var clickSlide, cursorAnimation, debugMode, isPaused, isTimeout, nextSlide, skill, skillIndex, skills;

  debugMode = false;

  skills = ["web", "languages", "math", "other"];

  skillIndex = 0;

  isPaused = false;

  isTimeout = false;

  $(function() {
    var i, j;
    $("#border-bottom").animate({
      width: "80vw"
    }, 500);
    $("#border-right, #border-left").delay(500).animate({
      height: "80vh"
    }, 500);
    $("#border-top-white").delay(1000).animate({
      width: "0vw"
    }, 500);
    $("#title-words").delay(1500).fadeIn(500);
    $("#picture").delay(1500).fadeIn(500).animate({
      right: "40vw"
    }, 500);
    $("#introduction, #portfolio, #skills, #email, footer").delay(2200).fadeIn(300);
    setInterval(function() {
      cursorAnimation();
      return 1000;
    });
    skill(); // initial
    for (i = j = 2; j <= 4; i = ++j) {
      $("#block-" + i).fadeOut(function() {});
    }
    $("#circle-1, #circle-2, #circle-3, #circle-4").click(function() {
      if (!isPaused) {
        console.log('click');
        isPaused = true;
        isTimeout = true;
        setTimeout(function() {
          return isPaused = false;
        }, 1000);
        setTimeout(function() {
          return isTimeout = false;
        }, 5000);
        return clickSlide("#" + this.id);
      }
    });
    return setInterval(function() {
      if (!(isPaused || isTimeout || debugMode)) {
        console.log('setInterval');
        isPaused = true;
        setTimeout(function() {
          return isPaused = false;
        }, 1000);
        return nextSlide();
      }
    }, 5000);
  });

  cursorAnimation = function() {
    return $("#cursor").animate({
      opacity: 0
    }, '10', 'swing').animate({
      opacity: 1
    }, '10', 'swing');
  };

  skill = function() {
    var currentTitle, i, j, ref, speed;
    speed = 100;
    currentTitle = $("#skill").text();
    for (i = j = 0, ref = currentTitle.length; (0 <= ref ? j <= ref : j >= ref); i = 0 <= ref ? ++j : --j) {
      (function(i) {
        return setTimeout((function() {
          return $("#skill").text(currentTitle.substr(0, currentTitle.length - i));
        }), speed * i);
      })(i);
    }
    return setTimeout((function() {
      var k, ref1, results;
      results = [];
      for (i = k = 0, ref1 = skills[skillIndex].length; (0 <= ref1 ? k <= ref1 : k >= ref1); i = 0 <= ref1 ? ++k : --k) {
        results.push((function(i) {
          return setTimeout((function() {
            return $("#skill").append(skills[skillIndex][i]);
          }), speed * i);
        })(i));
      }
      return results;
    }), speed * currentTitle.length);
  };

  clickSlide = function(newBlockCircle) {
    var currentBlock, currentBlockCircle, newBlock;
    currentBlock = "#" + $("#skills-showcase").find(".active-block")[0].id;
    currentBlockCircle = "#circle-" + currentBlock.slice(-1);
    newBlock = "#block-" + newBlockCircle.slice(-1);
    skillIndex = newBlockCircle.slice(-1) - 1;
    skill();
    // newBlockCircle is a parameter
    if (newBlock !== currentBlock) {
      $(currentBlock).fadeOut(function() {
        return $(newBlock).fadeIn(function() {});
      });
      $(currentBlock).removeClass("active-block");
      $(newBlock).addClass("active-block");
      $(currentBlockCircle).removeClass("fas");
      $(currentBlockCircle).addClass("far");
      $(newBlockCircle).removeClass("far");
      return $(newBlockCircle).addClass("fas");
    }
  };

  // console.log(currentBlock)
  // console.log(currentBlockCircle)
  // console.log(newBlock)
  // console.log(newBlockCircle)
  nextSlide = function() {
    var currentBlock, newBlockCircle, nextNumber;
    currentBlock = "#" + $("#skills-showcase").find(".active-block")[0].id;
    nextNumber = (parseInt(currentBlock.slice(-1))) % 4 + 1;
    newBlockCircle = "#circle-" + nextNumber;
    return clickSlide(newBlockCircle);
  };

}).call(this);
