// Generated by CoffeeScript 1.12.2
(function() {
  $(function() {
    $("#border-bottom").animate({
      width: "80vw"
    }, 1000);
    $("#border-right").delay(1000).animate({
      height: "80vh"
    }, 1000);
    $("#border-left").delay(1000).animate({
      height: "80vh"
    }, 1000);
    $("#border-top-white").delay(2000).animate({
      width: "0vw"
    }, 1000);
    $("#title-words").delay(3000).fadeIn(500);
    return $("#picture").delay(3000).fadeIn(500);
  });

}).call(this);
